### ISSUE TITLE
INFO

### ISSUE THREAD

**Issue by a3rgames** [elenawinters/ewdamagenumbers#1]
hi its nice to see something for free 

i want to ask you if you can upload this greate script to fivem forum?
beacuse there is othere players like me want this script on forum

**Comment by elenawinters** [comment]
I'm hoping to get around to it soon. I currently don't meet the criteria to post on the FiveM Forums, specifically in the section for scripts like these. When I'm able to though, I'll through it up there!

**Comment by elenawinters** [comment]
Didn't mean to close it!

**Comment by elenawinters** [comment]
I've created a forum release for this script, you can find it here: https://forum.cfx.re/t/ew-damage-numbers/4905531

**Comment by hasidu** [comment]
THANK YOU
